export const CALL_API = 'CALL_API';
export const CREATE_CONTACT = 'CREATE_CONTACT';
export const CREATE_CONTACT_SUCCEEDED = 'CREATE_CONTACT_SUCCEEDED';
export const CREATE_CONTACT_FAILED = 'CREATE_CONTACT_FAILED';
