export const CALL_API = 'CALL_API';
export const CREATE_CONTACT = 'CREATE_CONTACT';
export const CREATE_CONTACT_SUCCEEDED = 'CREATE_CONTACT_SUCCEEDED';
export const CREATE_CONTACT_FAILED = 'CREATE_CONTACT_FAILED';
export const CREATE_ALGORITHM_DESCRIPTION = 'CREATE_ALGORITHM_DESCRIPTION';
export const CREATE_ALGORITHM_DESCRIPTION_SUCCEEDED = 'CREATE_ALGORITHM_DESCRIPTION_SUCCEEDED';
export const CREATE_ALGORITHM_DESCRIPTION_FAILED = 'CREATE_ALGORITHM_DESCRIPTION_FAILED';
