# Optional opensearch custom config that can be used to debug opensearch separate from the stack
# Import this config to enable security in opensearch - See source: https://opensearch.org/docs/1.0/opensearch/install/docker/#configure-opensearch 
cluster.name: opensearch-cluster
node.name: opensearch-main
node.master: true
discovery.type: single-node
bootstrap.memory_lock: true 
OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
http.cors.allow-origin: "*,http://localhost:9000/,http://localhost:8000,http://localhost:8000/,http://localhost:8000/v2/,https://localhost:8000/v2"
http.cors.enabled: true
http.cors.allow-headers: "X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization"
http.cors.allow-credentials: true
plugins.security.disabled: true # this option should be used for development and test ONLY