import fastapi_permissions

ACLS = {
    fastapi_permissions.Everyone: [{"action": "view", "status": "PUBLISHED"}],
    fastapi_permissions.Authenticated: [{"action": "view"}],
    "owner": [
        {"action": "delete", "status": "DRAFT"},
        {"action": "request_review", "status": "DRAFT"},
        {"action": "cancel_closed_review_request", "status": "CLOSED_REVIEW_REQUESTED"},
        {"action": "request_publication", "status": "OPEN_REVIEW"},
        {"action": "cancel_publication_request", "status": "PUBLICATION_REQUESTED"},
        {"action": "create_new_version", "status": "PUBLISHED"},
        {"action": "bump_minor_version", "status": "PUBLISHED"},
        {"action": "join_reviewers", "deny": True},
        {"action": "comment"},
        {"action": "edit"},
        {"action": "invite_authors"},
        {"action": "offer_ownership"},
        {"action": "view_authors"},
        {"action": "view_owner"},
        {"action": "update"},
        {"action": "invite_authors"},
    ],
    "authors": [
        {"action": "join_reviewers", "deny": True},
        {"action": "comment"},
        {"action": "edit"},
        {"action": "view_authors"},
        {"action": "view_owner"},
        {"action": "update"},
        {"action": "create_new_version", "status": "PUBLISHED"},
        {"action": "bump_minor_version", "status": "PUBLISHED"},
    ],
    "reviewers": [
        {"action": "recieve_ownership", "deny": True},
        {"action": "join_authords", "deny": True},
        {"action": "comment"},
        {"action": "view_reviewers"},
        {"action": "view_authors"},
        {"action": "view_owner"},
        {"action": "mark_review_done", "status": "CLOSED_REVIEW"},
    ],
    "role:contributor": [
        {"action": "receive_ownership"},
        {"action": "join_authors"},
        {"action": "join_reviewers"},
    ],
    "role:curator": [
        {"action": "receive_ownership", "deny": True},
        {"action": "join_authors", "deny": True},
        {"action": "join_reviewers", "deny": True},
        {"action": "comment"},
        {"action": "view_reviewers"},
        {"action": "view_authors"},
        {"action": "view_owner"},
        {"action": "invite_reviewers"},
        {"action": "invite_authors"},
        {"action": "offer_ownership"},
        {"action": "delete"},
        {"action": "deny_closed_review_request", "status": "CLOSED_REVIEW_REQUESTED"},
        {"action": "accept_closed_review_request", "status": "CLOSED_REVIEW_REQUESTED"},
        {"action": "open_review", "status": "CLOSED_REVIEW"},
        {"action": "deny_publication_request", "status": "PUBLICATION_REQUESTED"},
        {"action": "accept_publication_request", "status": "PUBLICATION_REQUESTED"},
        {"action": "publish", "status": "PUBLICATION"},
    ],
}
