name: Lint and Test code base
on: 
  push:   
  pull_request: 


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup python 3
      uses: actions/setup-python@v2
      with: 
        python-version: 3.8
    - name: Install dependencies
      run: | 
        sudo apt-get install libxml2-dev libxmlsec1-dev
        pip install --upgrade pip setuptools wheel 
        pip install -e .[dev] --no-binary xmlsec
        pre-commit run --all-files
  test: 
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: Setup python 3
      uses: actions/setup-python@v2
      with: 
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[test]
        pytest tests --cov app --cov-report term-missing --ignore=venev

# name: Deploy APT API
# on:
#   push:
#     branches:
#       - master
#       - develop
#       - feature/api-v2-ci-cd # for testing purposes
# jobs: 

