name: Lint and Test code base
on: 
  push:   
  pull_request: 

# TODO: implement caching!
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup python 3
      uses: actions/setup-python@v2
      with: 
        python-version: 3.8
    - name: Install dependencies
      run: | 
        sudo apt-get update 
        sudo apt-get install -y  libxml2-dev libxmlsec1-dev libxmlsec1-openssl
        pip install --upgrade pip setuptools wheel 
        pip install -e .[dev] --no-binary xmlsec
        pre-commit run --all-files
  test: 
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: Setup python 3
      uses: actions/setup-python@v2
      with: 
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo apt-get update 
        sudo apt-get install -y  libxml2-dev libxmlsec1-dev libxmlsec1-openssl
        sudo apt-get install texlive-latex-recommended texlive-xetex latexmk
        pip install --upgrade pip setuptools wheel 
        pip install -e .[test] --no-binary xmlsec
        pytest tests --cov app --cov-report term-missing --ignore=venev
